workspace:
  base: /go
  path: src/github.com/quintoandar/drone-eb-checker

pipeline:
  test:
    image: golang:1.8
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out

  build:
    image: golang:1.8
    commands: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

